name: Deploy Bundle@dev

on:
  push:
    branches: [ dev ]

jobs:
  build:

    runs-on: self-hosted

    steps:
      - name: cleanup
        run: echo ${{secrets.DEPLOY_PASSWORD}} | sudo -S chown -R $USER:$USER /home/github/actions-runner/_work/nitro-react
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: Install & Build
        run: |
          npm run build:prod
      - name: Archive Artifacts
        uses: actions/upload-artifact@v2
        with:
          path: |
            build
      - name: Upload Artifacts
        uses: actions/upload-artifact@v2
        with:
          host: ${{ secrets.HOST }}
          port: ${{ secrets.PORT }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSHKEY }}
          path: |
            build
          target: "/var/www/nitrots.co/domains/prod.nitrots.co/html"
