name: Deploy Bundle@dev

on:
  push:
    branches: [ dev ]

jobs:
  build:

    runs-on: self-hosted
    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install & Build
        run: |
          npm run build:prod
      - name: Archive Artifacts
        uses: actions/upload-artifact@v2
        with:
          path: |
            build
      - name: Upload Artifacts
        uses: actions/upload-artifact@v2
        with:
          host: ${{ secrets.HOST }}
          port: ${{ secrets.PORT }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSHKEY }}
          path: |
            build
          target: "/var/www/nitrots.co/domains/prod.nitrots.co/html"
